// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScholarshipManagementSystem.Data;

namespace ScholarshipManagementSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210910104810_add_column_year")]
    partial class add_column_year
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UsernameChangeLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.AutoSMSApi.SMSAPIService", b =>
                {
                    b.Property<int>("SMSAPIServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BalanceEnquiryURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mask")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageExpiryURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SendSMSURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SMSAPIServiceId");

                    b.ToTable("SMSAPIService", "sms");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.AutoSMSApi.SMSAPIServiceAuditTrail", b =>
                {
                    b.Property<int>("SMSAPIServiceAuditTrailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DestinationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageFor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SendOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TextLength")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SMSAPIServiceAuditTrailId");

                    b.ToTable("SMSAPIServiceAuditTrail", "sms");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.DAEInstitute", b =>
                {
                    b.Property<int>("DAEInstituteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAEYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Enrollment1stY")
                        .HasColumnType("int");

                    b.Property<int>("Enrollment2ndY")
                        .HasColumnType("int");

                    b.Property<int>("Enrollment3rdY")
                        .HasColumnType("int");

                    b.Property<string>("FaxNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FocalPersonEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FocalPersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FocalPersonPhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAbbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PercentageSlots")
                        .HasColumnType("real");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvienceId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DAEInstituteId");

                    b.HasIndex("DistrictId");

                    b.ToTable("DAEInstitute", "master");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.Degree", b =>
                {
                    b.Property<int>("DegreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QualificationLevelId")
                        .HasColumnType("int");

                    b.Property<string>("ResultSystem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DegreeId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("QualificationLevelId");

                    b.ToTable("Degree", "master");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.DegreeLevel", b =>
                {
                    b.Property<int>("DegreeLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DegreeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("DegreeLevelId");

                    b.HasIndex("DegreeId");

                    b.ToTable("DegreeLevel", "master");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.DegreeScholarshipLevel", b =>
                {
                    b.Property<int>("DegreeScholarshipLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DegreeLevelId")
                        .HasColumnType("int");

                    b.Property<int>("Enrollment")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchemeLevelId")
                        .HasColumnType("int");

                    b.Property<float>("Slot")
                        .HasColumnType("real");

                    b.HasKey("DegreeScholarshipLevelId");

                    b.HasIndex("DegreeLevelId");

                    b.HasIndex("SchemeLevelId");

                    b.ToTable("DegreeScholarshipLevel", "master");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.Discipline", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DisciplineId");

                    b.ToTable("Discipline", "master");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DistrictId");

                    b.HasIndex("DivisionId");

                    b.ToTable("District", "master");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.DistrictDetail", b =>
                {
                    b.Property<int>("DistrictDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CensesYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<float>("FemaleRatio")
                        .HasColumnType("real");

                    b.Property<float>("GrowthRate")
                        .HasColumnType("real");

                    b.Property<float>("MPIDifferenceFromStatndard")
                        .HasColumnType("real");

                    b.Property<float>("MPIScore")
                        .HasColumnType("real");

                    b.Property<float>("MaleRatio")
                        .HasColumnType("real");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("DistrictDetailId");

                    b.HasIndex("DistrictId");

                    b.ToTable("DistrictDetail", "master");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.Division", b =>
                {
                    b.Property<int>("DivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvienceId")
                        .HasColumnType("int");

                    b.HasKey("DivisionId");

                    b.HasIndex("ProvienceId");

                    b.ToTable("Division", "master");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.Faculty", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FacultyId");

                    b.ToTable("Faculty", "master");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.Institute", b =>
                {
                    b.Property<int>("InstituteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaxNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FocalPersonEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FocalPersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FocalPersonPhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstituteTypeId")
                        .HasColumnType("int");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAbbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvienceId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstituteId");

                    b.HasIndex("InstituteTypeId");

                    b.HasIndex("ProvienceId");

                    b.ToTable("Institute", "master");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.InstituteDepartment", b =>
                {
                    b.Property<int>("InstituteDepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int");

                    b.Property<string>("FocalPersonContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FocalPersonDesignation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FocalPersonEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FocalPersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstituteFacultyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstituteDepartmentId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("InstituteFacultyId");

                    b.ToTable("InstituteDepartment", "master");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.InstituteFaculty", b =>
                {
                    b.Property<int>("InstituteFacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("FocalPersonContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FocalPersonDesignation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FocalPersonEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FocalPersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstituteId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstituteFacultyId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("InstituteId");

                    b.ToTable("InstituteFaculty", "master");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.InstituteType", b =>
                {
                    b.Property<int>("InstituteTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstituteTypeId");

                    b.ToTable("InstituteType", "master");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.Preference", b =>
                {
                    b.Property<int>("PreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("BSProfDistrictThresholdFor1stY")
                        .HasColumnType("real");

                    b.Property<float>("BSProfThresholdForClass")
                        .HasColumnType("real");

                    b.Property<float>("DAEThreshold")
                        .HasColumnType("real");

                    b.Property<float>("DOMSBachelor1stYQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("DOMSBachelorClassQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("DOMSDAEQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("DOMSGraduationQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("DOMSIntermediateQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("DOMSMSQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("DOMSMasterQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("DOMSMatricQoutaPER")
                        .HasColumnType("real");

                    b.Property<int>("DistrictSlotMPIPer")
                        .HasColumnType("int");

                    b.Property<int>("DistrictSlotPopulationPer")
                        .HasColumnType("int");

                    b.Property<float>("GraduationPROF1stYSlot")
                        .HasColumnType("real");

                    b.Property<float>("GraduationPROF2ndYSlot")
                        .HasColumnType("real");

                    b.Property<float>("GraduationPROF3rdYSlot")
                        .HasColumnType("real");

                    b.Property<float>("GraduationPROF4thYSlot")
                        .HasColumnType("real");

                    b.Property<float>("GraduationPROF5thYSlot")
                        .HasColumnType("real");

                    b.Property<float>("GraduationThreshold")
                        .HasColumnType("real");

                    b.Property<float>("IOMSBachelor1stYQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("IOMSBachelorClassQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("IOMSDAEQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("IOMSGraduationQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("IOMSMSQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("IOMSMasterQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("IntermediateThreshold")
                        .HasColumnType("real");

                    b.Property<float>("MSSlot")
                        .HasColumnType("real");

                    b.Property<float>("MSThreshold")
                        .HasColumnType("real");

                    b.Property<float>("MasterSlot")
                        .HasColumnType("real");

                    b.Property<float>("MasterThreshold")
                        .HasColumnType("real");

                    b.Property<float>("MatricThreshold")
                        .HasColumnType("real");

                    b.Property<float>("POMSIntermediateQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("POMSMatricQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("PhDThreshold")
                        .HasColumnType("real");

                    b.Property<float>("Qouta")
                        .HasColumnType("real");

                    b.Property<float>("SQSEVIBachelor1stYQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("SQSEVIBachelorClassQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("SQSEVIDAEQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("SQSEVIGraduationQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("SQSEVIMSQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("SQSEVIMasterQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("SQSEVIMatricQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("SQSIntermediateEVIQouta")
                        .HasColumnType("real");

                    b.Property<float>("SQSOMSBachelor1stYQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("SQSOMSBachelorClassQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("SQSOMSDAEQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("SQSOMSGraduationQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("SQSOMSIntermediateQouta")
                        .HasColumnType("real");

                    b.Property<float>("SQSOMSMSQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("SQSOMSMasterQoutaPER")
                        .HasColumnType("real");

                    b.Property<float>("SQSOMSMatricQoutaPER")
                        .HasColumnType("real");

                    b.Property<int>("SchemeBacholarStipend")
                        .HasColumnType("int");

                    b.Property<int>("SchemeDAEStipend")
                        .HasColumnType("int");

                    b.Property<int>("SchemeGraduationStipend")
                        .HasColumnType("int");

                    b.Property<int>("SchemeIntermediateStipend")
                        .HasColumnType("int");

                    b.Property<int>("SchemeMSStipend")
                        .HasColumnType("int");

                    b.Property<int>("SchemeMasterStipend")
                        .HasColumnType("int");

                    b.Property<int>("SchemeMatricStipend")
                        .HasColumnType("int");

                    b.Property<float>("SlotBacholar1Y")
                        .HasColumnType("real");

                    b.Property<string>("SlotCalculationMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SlotDAE1Y")
                        .HasColumnType("real");

                    b.Property<float>("SlotDAE2Y")
                        .HasColumnType("real");

                    b.Property<float>("SlotDAE3Y")
                        .HasColumnType("real");

                    b.Property<float>("SlotFAFSc1Y")
                        .HasColumnType("real");

                    b.Property<float>("SlotFAFSc2Y")
                        .HasColumnType("real");

                    b.Property<float>("SlotMetric")
                        .HasColumnType("real");

                    b.HasKey("PreferenceId");

                    b.ToTable("Preference", "master");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.Provience", b =>
                {
                    b.Property<int>("ProvienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvienceId");

                    b.ToTable("Provience", "master");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.QualificationLevel", b =>
                {
                    b.Property<int>("QualificationLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QualificationLevelId");

                    b.ToTable("QualificationLevel", "master");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.SMSMassage", b =>
                {
                    b.Property<int>("SMSMassageTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Massage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SMSType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SMSMassageTypeId");

                    b.ToTable("SMSMassage", "master");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.Scheme", b =>
                {
                    b.Property<int>("SchemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScholarshipId")
                        .HasColumnType("int");

                    b.HasKey("SchemeId");

                    b.HasIndex("ScholarshipId");

                    b.ToTable("Scheme", "master");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.SchemeLevel", b =>
                {
                    b.Property<int>("SchemeLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstituteId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderBy")
                        .HasColumnType("int");

                    b.Property<int>("QualificationLevelId")
                        .HasColumnType("int");

                    b.Property<int>("SchemeId")
                        .HasColumnType("int");

                    b.HasKey("SchemeLevelId");

                    b.HasIndex("InstituteId");

                    b.HasIndex("QualificationLevelId");

                    b.HasIndex("SchemeId");

                    b.ToTable("SchemeLevel", "master");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.ScholarshipSetup.DAEInstituteQoutaBySchemeLevel", b =>
                {
                    b.Property<int>("DAEInstituteQoutaBySchemeLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClassEnrollment")
                        .HasColumnType("int");

                    b.Property<int>("DAEInstituteId")
                        .HasColumnType("int");

                    b.Property<float>("InstituteAdditionalSlot")
                        .HasColumnType("real");

                    b.Property<int>("PolicySRCForumId")
                        .HasColumnType("int");

                    b.Property<int>("SchemeLevelPolicyId")
                        .HasColumnType("int");

                    b.Property<float>("SlotAllocate")
                        .HasColumnType("real");

                    b.Property<int>("StipendAmount")
                        .HasColumnType("int");

                    b.Property<float>("Threshold")
                        .HasColumnType("real");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DAEInstituteQoutaBySchemeLevelId");

                    b.HasIndex("DAEInstituteId");

                    b.HasIndex("PolicySRCForumId");

                    b.HasIndex("SchemeLevelPolicyId");

                    b.ToTable("DAEInstituteQoutaBySchemeLevel");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.ScholarshipSetup.DistrictQoutaBySchemeLevel", b =>
                {
                    b.Property<int>("DistrictQoutaBySchemeLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentYearPopulation")
                        .HasColumnType("int");

                    b.Property<float>("DistrictAdditionalSlot")
                        .HasColumnType("real");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<float>("DistrictMPISlot")
                        .HasColumnType("real");

                    b.Property<float>("DistrictPopulationSlot")
                        .HasColumnType("real");

                    b.Property<float>("MPI")
                        .HasColumnType("real");

                    b.Property<float>("MPIDifferenceFromStatndard")
                        .HasColumnType("real");

                    b.Property<int>("PolicySRCForumId")
                        .HasColumnType("int");

                    b.Property<int>("SchemeLevelPolicyId")
                        .HasColumnType("int");

                    b.Property<int>("StipendAmount")
                        .HasColumnType("int");

                    b.Property<float>("Threshold")
                        .HasColumnType("real");

                    b.HasKey("DistrictQoutaBySchemeLevelId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("PolicySRCForumId");

                    b.HasIndex("SchemeLevelPolicyId");

                    b.ToTable("DistrictQoutaBySchemeLevel", "scholar");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.ScholarshipSetup.PolicySRCForum", b =>
                {
                    b.Property<int>("PolicySRCForumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEndorse")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherAttachment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyDocumentAttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SRCMinutesAttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScholarshipFiscalYearId")
                        .HasColumnType("int");

                    b.HasKey("PolicySRCForumId");

                    b.HasIndex("ScholarshipFiscalYearId");

                    b.ToTable("PolicySRCForum", "scholar");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.ScholarshipSetup.SchemeLevelPayment", b =>
                {
                    b.Property<int>("SchemeLevelPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("DOMS")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("POMS")
                        .HasColumnType("int");

                    b.Property<int>("SQSEVIs")
                        .HasColumnType("int");

                    b.Property<int>("SQSOMS")
                        .HasColumnType("int");

                    b.Property<int>("SchemeLevelId")
                        .HasColumnType("int");

                    b.Property<int>("ScholarshipFiscalYearId")
                        .HasColumnType("int");

                    b.Property<int>("ScholarshipQouta")
                        .HasColumnType("int");

                    b.HasKey("SchemeLevelPaymentId");

                    b.HasIndex("SchemeLevelId");

                    b.HasIndex("ScholarshipFiscalYearId");

                    b.ToTable("SchemeLevelPayment", "scholar");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.ScholarshipSetup.SchemeLevelPolicy", b =>
                {
                    b.Property<int>("SchemeLevelPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<float>("DOMS")
                        .HasColumnType("real");

                    b.Property<float>("POMS")
                        .HasColumnType("real");

                    b.Property<int>("PolicySRCForumId")
                        .HasColumnType("int");

                    b.Property<float>("SQSEVIs")
                        .HasColumnType("real");

                    b.Property<float>("SQSOMS")
                        .HasColumnType("real");

                    b.Property<int>("SchemeLevelId")
                        .HasColumnType("int");

                    b.Property<float>("ScholarshipSlot")
                        .HasColumnType("real");

                    b.HasKey("SchemeLevelPolicyId");

                    b.HasIndex("PolicySRCForumId");

                    b.HasIndex("SchemeLevelId");

                    b.ToTable("SchemeLevelPolicy", "scholar");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.ScholarshipSetup.Scholarship", b =>
                {
                    b.Property<int>("ScholarshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScholarshipId");

                    b.ToTable("Scholarship", "scholar");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.ScholarshipSetup.ScholarshipFiscalYear", b =>
                {
                    b.Property<int>("ScholarshipFiscalYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScholarshipFiscalYearId");

                    b.ToTable("ScholarshipFiscalYear", "scholar");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ScholarshipManagementSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ScholarshipManagementSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholarshipManagementSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ScholarshipManagementSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.DAEInstitute", b =>
                {
                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.Degree", b =>
                {
                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.QualificationLevel", "QualificationLevel")
                        .WithMany()
                        .HasForeignKey("QualificationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("QualificationLevel");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.DegreeLevel", b =>
                {
                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.Degree", "Degree")
                        .WithMany()
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Degree");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.DegreeScholarshipLevel", b =>
                {
                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.DegreeLevel", "DegreeLevel")
                        .WithMany()
                        .HasForeignKey("DegreeLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.SchemeLevel", "SchemeLevel")
                        .WithMany()
                        .HasForeignKey("SchemeLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DegreeLevel");

                    b.Navigation("SchemeLevel");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.District", b =>
                {
                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.DistrictDetail", b =>
                {
                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.Division", b =>
                {
                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.Provience", "Provience")
                        .WithMany()
                        .HasForeignKey("ProvienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provience");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.Institute", b =>
                {
                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.InstituteType", "InstituteType")
                        .WithMany()
                        .HasForeignKey("InstituteTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.Provience", "Provience")
                        .WithMany()
                        .HasForeignKey("ProvienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstituteType");

                    b.Navigation("Provience");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.InstituteDepartment", b =>
                {
                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.InstituteFaculty", "InstituteFaculty")
                        .WithMany()
                        .HasForeignKey("InstituteFacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("InstituteFaculty");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.InstituteFaculty", b =>
                {
                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Institute");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.Scheme", b =>
                {
                    b.HasOne("ScholarshipManagementSystem.Models.Domain.ScholarshipSetup.Scholarship", "Scholarship")
                        .WithMany()
                        .HasForeignKey("ScholarshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scholarship");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.MasterSetup.SchemeLevel", b =>
                {
                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.QualificationLevel", "QualificationLevel")
                        .WithMany()
                        .HasForeignKey("QualificationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.Scheme", "Scheme")
                        .WithMany()
                        .HasForeignKey("SchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institute");

                    b.Navigation("QualificationLevel");

                    b.Navigation("Scheme");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.ScholarshipSetup.DAEInstituteQoutaBySchemeLevel", b =>
                {
                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.DAEInstitute", "DAEInstitute")
                        .WithMany()
                        .HasForeignKey("DAEInstituteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholarshipManagementSystem.Models.Domain.ScholarshipSetup.PolicySRCForum", "SRCForum")
                        .WithMany()
                        .HasForeignKey("PolicySRCForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholarshipManagementSystem.Models.Domain.ScholarshipSetup.SchemeLevelPolicy", "SchemeLevelPolicy")
                        .WithMany()
                        .HasForeignKey("SchemeLevelPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DAEInstitute");

                    b.Navigation("SchemeLevelPolicy");

                    b.Navigation("SRCForum");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.ScholarshipSetup.DistrictQoutaBySchemeLevel", b =>
                {
                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholarshipManagementSystem.Models.Domain.ScholarshipSetup.PolicySRCForum", "SRCForum")
                        .WithMany()
                        .HasForeignKey("PolicySRCForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholarshipManagementSystem.Models.Domain.ScholarshipSetup.SchemeLevelPolicy", "SchemeLevelPolicy")
                        .WithMany()
                        .HasForeignKey("SchemeLevelPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("SchemeLevelPolicy");

                    b.Navigation("SRCForum");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.ScholarshipSetup.PolicySRCForum", b =>
                {
                    b.HasOne("ScholarshipManagementSystem.Models.Domain.ScholarshipSetup.ScholarshipFiscalYear", "ScholarshipFiscalYear")
                        .WithMany()
                        .HasForeignKey("ScholarshipFiscalYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScholarshipFiscalYear");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.ScholarshipSetup.SchemeLevelPayment", b =>
                {
                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.SchemeLevel", "SchemeLevel")
                        .WithMany()
                        .HasForeignKey("SchemeLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholarshipManagementSystem.Models.Domain.ScholarshipSetup.ScholarshipFiscalYear", "ScholarshipFiscalYear")
                        .WithMany()
                        .HasForeignKey("ScholarshipFiscalYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchemeLevel");

                    b.Navigation("ScholarshipFiscalYear");
                });

            modelBuilder.Entity("ScholarshipManagementSystem.Models.Domain.ScholarshipSetup.SchemeLevelPolicy", b =>
                {
                    b.HasOne("ScholarshipManagementSystem.Models.Domain.ScholarshipSetup.PolicySRCForum", "PolicySRCForum")
                        .WithMany()
                        .HasForeignKey("PolicySRCForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholarshipManagementSystem.Models.Domain.MasterSetup.SchemeLevel", "SchemeLevel")
                        .WithMany()
                        .HasForeignKey("SchemeLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicySRCForum");

                    b.Navigation("SchemeLevel");
                });
#pragma warning restore 612, 618
        }
    }
}
